### PR TITLE
Handle rtc json

### LINKED ISSUE #63: have csv_to_json return an error code.
If csv_to_json fails, report the error.

### PR DESCRIPTION
**Pull request by dvalinrh**
# Description
1) makes package_tools come from general_setup
2) Report failures from csv_to_json, and make sure the error code is reported back.

# Before/After Comparison
Before: if csv_to_json failed we would not record the error.
After: If csv_to_json fails, we now report the error.

# Clerical Stuff
This closes #63

Relates to JIRA: RPOPC-839

Command executed
home/ec2-user/workloads/autohpl-wrapper-2.1/auto_hpl/build_run_hpl.sh --run_user ec2-user --home_parent /home --iterations 1 --tuned_setting tuned_none_sys_file_ --host_config "m5.xlarge" --sysname "m5.xlarge" --sys_type aws  --use_pcp  --debug

output success
[ip-170-0-29-22.us-east-2.compute.internal:99642] MCW rank 0 is not bound (or bound to all available processors)
PCP metrics reset
Stopping PCP subset
Stop PCP
Results verified
updating: results_auto_hpl_virtual-guest.tar (deflated 92%)

csv_file
TV,N,NB,P,Q,Time,Gflops,Start_Date,End_Date
WR12R2R4,38400,256,1,1,295.74,1.2765e+02,2026-02-17T20:10:08Z,2026-02-17T20:16:05Z

Failed run output
Stop PCP
Class AutoHPL_Results not found in /workloads/autohpl-wrapper-2.1/auto_hpl/result_schema.py
Error: [Errno 2] No such file or directory: '/workloads/autohpl-wrapper-2.1/auto_hpl/result_schema.py'
Error: /root/test_tools/verify_results --schema_file /workloads/autohpl-wrapper-2.1/auto_hpl/result_schema.py --class_name AutoHPL_Results --file results_auto_hpl.json failed.
updating: results_auto_hpl_virtual-guest.tar (deflated 92%)

--debug output
[auto_fix.txt](https://github.com/user-attachments/files/25373711/auto_fix.txt)

### CODE REVIEW

File: auto_hpl/build_run_hpl.sh [hunk 1]
```diff
@@ -877,7 +877,18 @@ if [[ $to_use_pcp -eq 1 ]]; then
 fi
 cp $out_file results_auto_hpl.csv
 $TOOLS_BIN/csv_to_json $to_json_flags --csv_file results_auto_hpl.csv --output_file results_auto_hpl.json
-$TOOLS_BIN/verify_results $to_verify_flags --schema_file $script_dir/result_schema.py --class_name AutoHPL_Results --file results_auto_hpl.json
-rtc=$?
+if [[ $? -ne 0 ]]; then
+	echo Error: $TOOLS_BIN/csv_to_json $to_json_flags --csv_file results_auto_hpl.csv --output_file results_auto_hpl.json returned failure
+	rtc=2
```
Comment (frival) [inline auto_hpl/build_run_hpl.sh]: csv_to_json doesn't return a proper error code?

**Review by frival — COMMENTED** [review]
Just a question on csv_to_json and return code

**Review by kdvalin — CHANGES_REQUESTED** [review]

**Review by kdvalin — CHANGES_REQUESTED** [review]

**Review by kdvalin — APPROVED** [review]
LGTM
